language: ruby
install: true
script: true
deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: us-east-1
  app: manual50
  env: manual50
  bucket_name: travis50
  on:
    branch: master
notifications:
  slack:
    secure: 20SxvbJkjgk+pOHrxDqVdPmmjwRY3ItW8VKayGsUCEY9KAdGHea9At4g05kgrdUERzS7yM52ouRqaH59u/9KEvPsYu6bizji7TbGlb1tYnzLUGXnjrn3ukxXAyciHIlgMWe8xgg2ugiKRykgaZn36boErPOiNclKLwPwc6Eng4hseSC0oXl7z6NTVXXOvqvXZTdO7pwwN+jMsWYfA7RPlhdY2g4XGVscGmvr1EQec2ELnx1rw/vkNVzWT4gKtYAeNoXusoN79cI+S6COaaqCO/uDdPDEAt4cL2Y5syl762LhIJeymBMCEnC4urpFia9SlFLrLQ6gQE5uoUlaiAmdc1Md01vZ6na1WLn/xUX0S1trYjKs9A3flyLHcnEV89nGtt6dCd/cHfamQdb8rq6Zt5Jf0FXRCxZdgTeviX3wVnXWH/fRQq50zWWksre+G603v3GPbCmMf4UjehXwwWR3oSluMeVQ/4lXwm3zz348FaCEEWqqGug8wsJfAn684ZGCDf/vBXbyD+p9sXfs2/wcicLyyPR43QAXHuS3s16tmNHbZhZJ4V+dXDd9+PzaRh7rcTn3KyrCYKySQXHyTCu6wUdg6SUXVBm1kHN0HgAZLB5PPBSTF4dLSK3cGUja5n4aVeguwszPunneEV26/DsOUXJcwielMf7/ORRTYkT9MZ8=
